= Environment Setup

== Environment Access

You can access the environment in the following ways:

=== "Showroom" Terminal

Use the Terminal on the right side of "showroom" interface.

This should automatically SSH into the bastion host for your environment.

If not, notify your instructor.

=== SSH from your laptop to the bastion host

Go ahead and use your favorite terminal on your laptop to access the bastion host.

{ssh_command}

=== Run commands from your laptop

. You'll need to install `az` tools, if you don't have them.  See below.

== Tools Setup

=== MacOS

NOTE: See https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos[Azure Docs] for alternative install options.

. Install OpenShift CLI using homebrew

[source,bash,]
----
brew update && brew install openshift-cli
----

. Install Azure CLI using homebrew

[source,bash,]
----
brew update && brew install azure-cli
----

. Install sshuttle using homebrew

[source,bash,]
----
brew install sshuttle
----

=== On Your Linux Laptop (bastion already has it installed)

NOTE: See https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf[Azure Docs] for alternative install options.

. Import the Microsoft Keys

[source,bash]
----
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
----

. Add the Microsoft Yum Repository

[source,bash]
----
cat << EOF | sudo tee /etc/yum.repos.d/azure-cli.repo
[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
EOF
----

. Install Azure CLI

[source,bash]
----
sudo dnf install -y azure-cli sshuttle
----

. Install OpenShift CLI

[source,bash]
----
curl -LO https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/latest/openshift-client-linux.tar.gz
tar xvzf openshift-client-linux.tar.gz
sudo mv oc kubectl /usr/local/bin/
----

== Validate Command Line Tools

You will be using the `az` and `oc` command line tools throughout this lab.

. Verify that the `az` command line tool is installed:
+
[source,sh,role=execute]
----
az version
----
+
.Sample Output
[source,texinfo]
----
{
  "azure-cli": "2.54.0",
  "azure-cli-core": "2.54.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}
----

. Validate the version of the OpenShift CLI:
+
[source,sh,role=execute]
----
oc version
----
+
.Sample Output
[source,texinfo]
----
Client Version: 4.14.4
Kustomize Version: v5.0.1
----

== Prepare Azure Account for ARO

. Set Environment Variables for Azure

[source,bash,subs="+macros,+attributes",role=execute]
----
export GUID={guid}
export AZR_SP_ID={azure_service_principal_id}
export AZR_SP_PASS='{azure_service_principal_password}'
export AZR_TENANT_ID={azure_tenant}
export AZR_RESOURCE_GROUP=openenv-{guid}
export AZ_SUB_ID={azure_subscription}
----

. Log into the Azure CLI by running the following and then authorizing through your Web Browser

[source,bash,role=execute]
----
az login --subscription $AZ_SUB_ID
----

. Make sure you have enough Quota (change the location if you're not using `East US`)

[source,bash,role=execute]
----
az vm list-usage --location "East US" -o table
----

see <<adding-quota-to-aro-account>> if you have less than `36` Quota left for `Total Regional vCPUs`.

. Register Resource Providers

[source,bash]
----
az provider register -n Microsoft.RedHatOpenShift --wait
az provider register -n Microsoft.Compute --wait
az provider register -n Microsoft.Storage --wait
az provider register -n Microsoft.Authorization --wait
----

=== Get Red Hat Pull Secret

. Log into cloud.redhat.com

. Browse to https://cloud.redhat.com/openshift/install/azure/aro-provisioned

. click the *Download pull secret* button and remember where you saved it, you'll reference it later.
